use_frameworks!

target 'BMBlinkDemo_Example' do
  pod 'BMBlinkDemo', :path => '../'

  target 'BMBlinkDemo_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
